name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build-book.yaml
    with:
      environment_name: cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: notebooks/
  link-check:
    uses: ./.github/workflows/link-checker.yaml
    with:
      environment_name: cookbook-dev
      environment_file: environment.yml
      path_to_notebooks: notebooks/
